apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: Demo-keyvault-forMaven
    tenantId: 3d077662-f515-4f06-b98c-3387f05d1579
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
