name: Build Maven Docker and Push to ACR

on:
  #push:
  #  branches: [ "springboot3" ]
  #pull_request:
  #  branches: [ "springboot3" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: docker:24.0-dind  # Docker-in-Docker container
      options: --privileged      # Required for Docker inside container

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Azure login using Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3️⃣ Login to ACR
      - name: Login to ACR
        run: |
          az acr login --name springbootappmaven

      # 4️⃣ Set Docker image tag as commit SHA
      - name: Set Docker Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      # 5️⃣ Build Docker image (Maven build happens inside Dockerfile)
      - name: Build Docker Image
        run: docker build -t springbootappmaven.azurecr.io/springbootimage:${{ github.sha }} .

      # 6️⃣ Push Docker image to ACR
      - name: Push Docker Image
        run: docker push springbootappmaven.azurecr.io/springbootimage:${{ github.sha }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
            resource-group: ${{ secrets.AKS_RG }}
            cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Update Image Tag
        run: |
            sed -i "s|springboot-app:latest|springboot-app:${{ github.sha }}|g" k8s-deployment.yaml

      - name: Deploy to AKS
        run: kubectl apply -f k8s-deployment.yaml